### ISSUE TITLE
Sprint 6: Release 3 Summary

### ISSUE THREAD

**Issue by JamalG16** [milaroisin/SOEN390-VigilantCamera#34]
As a client, I want to be able to track the progress of the project.

* [ ]  Write a summary of the third release for the client.
* [x] Mockups for QR Scanner.

[Story Points: 3]
[Risk: Low]
[Priority: High]

**Comment by milaroisin** [comment]
@ggebran @DanielPri I've placed release summary in the Google Drive folder for ease of access.
